spring.application.name=InjurySystem

# ===============================
# THYMELEAF (optional tweak)
# ===============================
spring.thymeleaf.cache=false

# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
 
# Enable H2 Console in the browser
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
# Show SQL in console (great for teaching)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# EMAIL (Gmail SMTP)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=amoumen034@gmail.com
spring.mail.password=nkfo wkyq fmlh akkr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true